version: '3'

services:
    postgres:
        image: postgres
        container_name: credit-card-billing-postgres
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
            POSTGRES_DB: credit-card-billing

        ports:
            - 5432:5432

        volumes:
            - ./.postgres-data:/var/lib/postgresql/data
